.TH DMENUSTATUS 1 dmenustatus-0.10.2
.SH NAME
dmenustatus \- A lightweight status bar for dwm
.SH SYNOPSIS
.B dmenustatus
.SH DESCRIPTION
.B dmenustatus
is a minimal status monitor designed to print system information the dmenu statusbar area. It is intended to be used with the
.BR dwm (1)
window manager.
.SH CONFIGURATION
dmenustatus is configured by editing the source code (dmenustatus.c) and recompiling.
.SH LICENSE
GNU Affero General Public License v3.0
.SH AUTHORS
Quadsam <bugs@quadsam.com>